/* eslint-disable @typescript-eslint/ban-ts-comment */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BookCase(props) {
  // @ts-expect-error
  const { nodes, materials } = useGLTF<GLTFResult>('./bookcase.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bookcase_1 as THREE.BufferGeometry}
        material={materials['RS Material.10']}
        position={[-0.777, -0.62, -1.174]}
      />
    </group>
  )
}

useGLTF.preload('/bookcase.gltf')
