name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.devcontainer/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, cn]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Runs a single command using the runners shell
      - name: install node env
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '16.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build project
        run: |
          echo install dependencies
          yarn
          echo build project
          yarn build

      - name: Upload website to Aliyun OSS
        uses: ncuhome/ali-oss-website-action@v1.1.0
        id: upload
        with:
          folder: dist # 待上传的文件夹
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }} ## 通过 secrets 注入 ak
          accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: 2023-3d-demo # 要上传到的 bucket, 若不存在会自动新建
          endpoint: 'https://oss-cn-hangzhou.aliyuncs.com' # 指定区域的 oss endpoint
